sudo: required
dist: trusty
addons:
  firefox: "latest"
language: node_js
node_js:
  - "6"
before_install:
- "export DISPLAY=:99.0"
- sh -e /etc/init.d/xvfb start
- sleep 3
install:
  - npm install
before_script:
  - npm run webdriver:update
  - sleep 10
script:
  - npm run ci