sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
before_install:
- "export DISPLAY=:99.0"
- sh -e /etc/init.d/xvfb start
- sleep 3
install:
  - npm install
  - npm run webdriver:update
script:
  - npm run ci